# Generated by Django 5.1.6 on 2025-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='common/upload'),
        ),
    ]
