# Generated by Django 5.1.6 on 2025-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='common/default/no-profile-picture.png', upload_to='common/upload'),
        ),
    ]
